//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCP.Client.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public int ID { get; set; }
        public string KeyType { get; set; }
        public string KeyCode { get; set; }
        public string KeyContent { get; set; }
        public string KeyMemo { get; set; }
        public string Sort { get; set; }
        public string Memo0 { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string Memo3 { get; set; }
    }
}
